---
title: "Differential Expression Analysis plots"
author: "Julia Corell Sierra"
date: "2023-05-15"
output: html_document
---

### Visualizations

```{r}
anno_file <- read.table("/path/to/annotation_results/curated_unitas_withtiny_annotation.tsv", sep="\t", header = TRUE)
cfg_file <- read.delim("/path/to/exogenous_sRNAs_results/centrifuge_anno_final.tsv", sep="\t", header=TRUE)
res_T1acute_tb <- read.table("/path/to/DEA_results/results_DE_T1acute.tsv", sep="\t", header=TRUE)
res_T1mild_tb <- read.table("/path/to/DEA_results/results_DE_T1mild.tsv", sep="\t", header=TRUE)
res_T2acute_tb <- read.table("/path/to/DEA_results/results_DE_T2acute.tsv", sep="\t", header=TRUE)
res_T2mild_tb <- read.table("/path/to/DEA_results/results_DE_T2mild.tsv", sep="\t", header=TRUE)
```

Merge both annotations (Unitas and taxonomical info derived from Centrifuge).

```{r}
DE_T1acute_ann <- merge(res_T1acute_tb, anno_file, by.x = "seq", by.y = "Seq", all.x = TRUE)
DE_T1acute_ann <- merge(DE_T1acute_ann, cfg_file, by.x="seq", by.y="Seq", all.x=TRUE)
DE_T1acute_ann$ID.x <- ifelse(is.na(DE_T1acute_ann$ID.x), DE_T1acute_ann$ID.y, DE_T1acute_ann$ID.x)
DE_T1acute_ann$ID.y <- NULL
names(DE_T1acute_ann)[names(DE_T1acute_ann) == 'ID.x'] <- 'ID'
DE_T1acute_ann$RNA_class <- ifelse(!is.na(DE_T1acute_ann$taxID), "Microorganism", DE_T1acute_ann$RNA_class)
```

```{r}
DE_T1mild_ann <- merge(res_T1mild_tb, anno_file, by.x = "seq", by.y = "Seq", all.x = TRUE)
DE_T1mild_ann <- merge(DE_T1mild_ann, cfg_file, by.x="seq", by.y="Seq", all.x=TRUE)
DE_T1mild_ann$ID.x <- ifelse(is.na(DE_T1mild_ann$ID.x), DE_T1mild_ann$ID.y, DE_T1mild_ann$ID.x)
DE_T1mild_ann$ID.y <- NULL
names(DE_T1mild_ann)[names(DE_T1mild_ann) == 'ID.x'] <- 'ID'
DE_T1mild_ann$RNA_class <- ifelse(!is.na(DE_T1mild_ann$taxID), "Microorganism", DE_T1mild_ann$RNA_class)
```

```{r}
DE_T2acute_ann <- merge(res_T2acute_tb, anno_file, by.x = "seq", by.y = "Seq", all.x = TRUE)
DE_T2acute_ann <- merge(DE_T2acute_ann, cfg_file, by.x="seq", by.y="Seq", all.x=TRUE)
DE_T2acute_ann$ID.x <- ifelse(is.na(DE_T2acute_ann$ID.x), DE_T2acute_ann$ID.y, DE_T2acute_ann$ID.x)
DE_T2acute_ann$ID.y <- NULL
names(DE_T2acute_ann)[names(DE_T2acute_ann) == 'ID.x'] <- 'ID'
DE_T2acute_ann$RNA_class <- ifelse(!is.na(DE_T2acute_ann$taxID), "Microorganism", DE_T2acute_ann$RNA_class)
```

```{r}
DE_T2mild_ann <- merge(res_T2mild_tb, anno_file, by.x = "seq", by.y = "Seq", all.x = TRUE)
DE_T2mild_ann <- merge(DE_T2mild_ann, cfg_file, by.x="seq", by.y="Seq", all.x=TRUE)
DE_T2mild_ann$ID.x <- ifelse(is.na(DE_T2mild_ann$ID.x), DE_T2mild_ann$ID.y, DE_T2mild_ann$ID.x)
DE_T2mild_ann$ID.y <- NULL
names(DE_T2mild_ann)[names(DE_T2mild_ann) == 'ID.x'] <- 'ID'
DE_T2mild_ann$RNA_class <- ifelse(!is.na(DE_T2mild_ann$taxID), "Microorganism", DE_T2mild_ann$RNA_class)
```

### MA plots

#### T1 acute

```{r}
## Create another column to indicate the type of RNAs only if it is significant
DE_T1acute_ann$Class_toplot <- ifelse(is.na(DE_T1acute_ann$RNA_class), "Other", DE_T1acute_ann$RNA_class)
DE_T1acute_ann$Class_toplot <- ifelse(grepl("miRNA-like|lncRNA|protein_coding|misc_RNA|rRNA|Mt_RNA|scaRNA", DE_T1acute_ann$RNA_class), "Other", DE_T1acute_ann$Class_toplot)
DE_T1acute_ann$Class_toplot <- ifelse(grepl("piR-cluster", DE_T1acute_ann$RNA_class), "piRNA", DE_T1acute_ann$Class_toplot)
DE_T1acute_ann$Class_toplot <- ifelse(DE_T1acute_ann$padj < 0.05, DE_T1acute_ann$Class_toplot, "Non-significant")
DE_T1acute_ann$Class_toplot <- factor(DE_T1acute_ann$Class_toplot, levels=c("miRNA", "tyRNA", "tRNA-derived", "snRNA", "snoRNA", "piRNA", "Microorganism", "Other", "Non-significant"))
```

```{r}
## MAplot
n_sRNAs_up <- DE_T1acute_ann %>% filter(!Class_toplot %in% c("Non-significant", "Other", "Microorganism")) %>% filter(lfcShrunk > 0) %>% nrow()
n_micro_up <- DE_T1acute_ann %>% filter(Class_toplot == "Microorganism") %>% filter(lfcShrunk > 0) %>% nrow()
n_other_up <- DE_T1acute_ann %>% filter(Class_toplot == "Other") %>% filter(lfcShrunk > 0) %>% nrow()
n_sRNAs_down <- DE_T1acute_ann %>% filter(!Class_toplot %in% c("Non-significant", "Other", "Microorganism")) %>% filter(lfcShrunk < 0) %>% nrow()
n_micro_down <- DE_T1acute_ann %>% filter(Class_toplot == "Microorganism") %>% filter(lfcShrunk < 0) %>% nrow()
n_other_down <- DE_T1acute_ann %>% filter(Class_toplot == "Other") %>% filter(lfcShrunk < 0) %>% nrow()
text_label <- paste("Up-regulated:\nsRNAs: ",  n_sRNAs_up, "\nOther: ", n_other_up,"\nMicroorg: ", n_micro_up, collapse="\n")
text_label_down <- paste("Down-regulated:\nsRNAs: ",  n_sRNAs_down, "\nOther: ", n_other_down,"\nMicroorg: ", n_micro_down, collapse="\n")
ggplot(DE_T1acute_ann, aes(x = baseMean, y = lfcShrunk, colour = Class_toplot)) +
    geom_point(data = subset(DE_T1acute_ann, Class_toplot == "Non-significant"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.2) +
    geom_point(data = subset(DE_T1acute_ann, Class_toplot == "Other"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.3) +
    geom_point(data = subset(DE_T1acute_ann, Class_toplot == "Microorganism"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.3) +
    geom_point(data = subset(DE_T1acute_ann, Class_toplot == "miRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.9) +
    geom_point(data = subset(DE_T1acute_ann, Class_toplot == "snRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    #geom_point(data = subset(DE_T1acute_ann, Class_toplot == "scaRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    geom_point(data = subset(DE_T1acute_ann, Class_toplot == "snoRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    geom_point(data = subset(DE_T1acute_ann, Class_toplot == "tRNA-derived"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    geom_point(data = subset(DE_T1acute_ann, Class_toplot == "tyRNA"), aes(x = baseMean, y =lfcShrunk), size=0.65, alpha=0.8) +
    #scale_alpha_discrete(range = c(0.9, 0.2)) +
    ggtitle("Severe (T1) expression") +
    xlab("baseMean") + 
    ylab("Log2 fold change") +
    scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
        labels = trans_format("log10", math_format(10^.x)))+
    scale_colour_manual(values = c("#d53e4f", "#3288bd", "#ff8d50", "#b78bc0","#50ff75", "#CDAC8E", "#c9eeea", "#b2bbba"),  name = "",
                        breaks = c("miRNA","tRNA-derived", "snRNA", "snoRNA", "tyRNA", "Microorganism", "Other", "Non-significant")) +
    theme_light() +
    theme(plot.title = element_text(size = rel(2), hjust = 0.5),
          axis.title = element_text(size = rel(1.5)),
          panel.grid = element_blank()) +
    guides(color = guide_legend(override.aes = list(size = 3))) +
    annotate("text", x=40000, y=20, label=text_label, vjust=1, hjust=0, angle=0, size=4.5) +
    annotate("text", x=40000, y=-9, label=text_label_down, vjust=1, hjust=0, angle=0, size=4.5) +
    theme(legend.position = "none",
          axis.text.x = element_text(size=16, color="black"),
          axis.text.y = element_text(size=16, color="black"),
          axis.line.x = element_line(color="black"),
          axis.line.y = element_line(color="black")) +
    geom_hline(yintercept=0, size=0.3, color="darkgrey") + ylim(-15,20)

ggsave("/path/to/DEA_results/Visualizations/MAplot_T1acute_micro.png", height = 7, width = 8.5)
```


#### T1 mild
```{r}
## Create another column to indicate the type of RNAs only if it is significant
DE_T1mild_ann$Class_toplot <- ifelse(is.na(DE_T1mild_ann$RNA_class), "Other", DE_T1mild_ann$RNA_class)
DE_T1mild_ann$Class_toplot <- ifelse(grepl("miRNA-like|lncRNA|protein_coding|misc_RNA|rRNA|Mt_RNA|scaRNA", DE_T1mild_ann$RNA_class), "Other", DE_T1mild_ann$Class_toplot)
DE_T1mild_ann$Class_toplot <- ifelse(grepl("piR-cluster", DE_T1mild_ann$RNA_class), "piRNA", DE_T1mild_ann$Class_toplot)
DE_T1mild_ann$Class_toplot <- ifelse(DE_T1mild_ann$padj < 0.05, DE_T1mild_ann$Class_toplot, "Non-significant")
DE_T1mild_ann$Class_toplot <- factor(DE_T1mild_ann$Class_toplot,  levels=c("miRNA", "tyRNA", "tRNA-derived", "snRNA", "snoRNA",  "piRNA", "Microorganism", "Other", "Non-significant"))
```

```{r}
## MAplot
n_sRNAs_up <- DE_T1mild_ann %>% filter(!Class_toplot %in% c("Non-significant", "Other", "Microorganism")) %>% filter(lfcShrunk > 0) %>% nrow()
n_micro_up <- DE_T1mild_ann %>% filter(Class_toplot == "Microorganism") %>% filter(lfcShrunk > 0) %>% nrow()
n_other_up <- DE_T1mild_ann %>% filter(Class_toplot == "Other") %>% filter(lfcShrunk > 0) %>% nrow()
n_sRNAs_down <- DE_T1mild_ann %>% filter(!Class_toplot %in% c("Non-significant", "Other", "Microorganism")) %>% filter(lfcShrunk < 0) %>% nrow()
n_micro_down <- DE_T1mild_ann %>% filter(Class_toplot == "Microorganism") %>% filter(lfcShrunk < 0) %>% nrow()
n_other_down <- DE_T1mild_ann %>% filter(Class_toplot == "Other") %>% filter(lfcShrunk < 0) %>% nrow()
text_label <- paste("Up-regulated:\nsRNAs: ",  n_sRNAs_up, "\nOther: ", n_other_up,"\nMicroorg: ", n_micro_up, collapse="\n")
text_label_down <- paste("Down-regulated:\nsRNAs: ",  n_sRNAs_down, "\nOther: ", n_other_down,"\nMicroorg: ", n_micro_down, collapse="\n")
ggplot(DE_T1mild_ann, aes(x = baseMean, y = lfcShrunk, colour = Class_toplot)) +
    geom_point(data = subset(DE_T1mild_ann, Class_toplot == "Non-significant"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.2) +
    geom_point(data = subset(DE_T1mild_ann, Class_toplot == "Other"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.3) +
    geom_point(data = subset(DE_T1mild_ann, Class_toplot == "Microorganism"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.3) +
    geom_point(data = subset(DE_T1mild_ann, Class_toplot == "miRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.9) +
    geom_point(data = subset(DE_T1mild_ann, Class_toplot == "snRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    #geom_point(data = subset(DE_T1mild_ann, Class_toplot == "scaRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    geom_point(data = subset(DE_T1mild_ann, Class_toplot == "snoRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    #geom_point(data = subset(DE_T1mild_ann, Class_toplot == "piRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    geom_point(data = subset(DE_T1mild_ann, Class_toplot == "tRNA-derived"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    geom_point(data = subset(DE_T1mild_ann, Class_toplot == "tyRNA"), aes(x = baseMean, y =lfcShrunk), size=0.65, alpha=0.8) +
    #scale_alpha_discrete(range = c(0.9, 0.2)) +
    ggtitle("Moderate (T1) expression") +
    xlab("baseMean") + 
    ylab("Log2 fold change") +
    scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
        labels = trans_format("log10", math_format(10^.x))) + 
    scale_colour_manual(values = c("#d53e4f", "#3288bd", "#ff8d50", "#b78bc0", "#50ff75", "#CDAC8E", "#c9eeea", "#b2bbba"),  name = "",
                        breaks = c("miRNA","tRNA-derived", "snRNA", "snoRNA", "tyRNA", "Microorganism", "Other", "Non-significant")) +
    theme_light() +
    theme(plot.title = element_text(size = rel(2), hjust = 0.5),
          axis.title = element_text(size = rel(1.5)),
          panel.grid = element_blank()) +
    guides(color = guide_legend(override.aes = list(size = 3))) +
    annotate("text", x=40000, y=20, label=text_label, vjust=1, hjust=0, angle=0, size=4.5) +
    annotate("text", x=40000, y=-9, label=text_label_down, vjust=1, hjust=0, angle=0, size=4.5) +
    theme(legend.position = "none",
          axis.text.x = element_text(size=16, color="black"),
          axis.text.y = element_text(size=16, color="black"),
          axis.line.x = element_line(color="black"),
          axis.line.y = element_line(color="black")) +
    geom_hline(yintercept=0, size=0.3, color="darkgrey") + ylim(-15,20)

ggsave("/path/to/DEA_results/Visualizations/MAplot_T1mild_micro.png", height = 7, width = 8.5)
```

#### T2 acute

```{r}
## Create another column to indicate the type of RNAs only if it is significant
DE_T2acute_ann$Class_toplot <- ifelse(is.na(DE_T2acute_ann$RNA_class), "Other", DE_T2acute_ann$RNA_class)
DE_T2acute_ann$Class_toplot <- ifelse(grepl("miRNA-like|lncRNA|protein_coding|misc_RNA|rRNA|Mt_RNA|scaRNA", DE_T2acute_ann$RNA_class), "Other", DE_T2acute_ann$Class_toplot)
DE_T2acute_ann$Class_toplot <- ifelse(grepl("piR-cluster", DE_T2acute_ann$RNA_class), "piRNA", DE_T2acute_ann$Class_toplot)
DE_T2acute_ann$Class_toplot <- ifelse(DE_T2acute_ann$padj < 0.05, DE_T2acute_ann$Class_toplot, "Non-significant")
DE_T2acute_ann$Class_toplot <- factor(DE_T2acute_ann$Class_toplot, levels=c("miRNA", "tyRNA", "tRNA-derived", "snRNA", "snoRNA", "piRNA", "Microorganism", "Other", "Non-significant"))
```

```{r}
## MAplot
n_sRNAs_up <- DE_T2acute_ann %>% filter(!Class_toplot %in% c("Non-significant", "Other", "Microorganism")) %>% filter(lfcShrunk > 0) %>% nrow()
n_micro_up <- DE_T2acute_ann %>% filter(Class_toplot == "Microorganism") %>% filter(lfcShrunk > 0) %>% nrow()
n_other_up <- DE_T2acute_ann %>% filter(Class_toplot == "Other") %>% filter(lfcShrunk > 0) %>% nrow()
n_sRNAs_down <- DE_T2acute_ann %>% filter(!Class_toplot %in% c("Non-significant", "Other", "Microorganism")) %>% filter(lfcShrunk < 0) %>% nrow()
n_micro_down <- DE_T2acute_ann %>% filter(Class_toplot == "Microorganism") %>% filter(lfcShrunk < 0) %>% nrow()
n_other_down <- DE_T2acute_ann %>% filter(Class_toplot == "Other") %>% filter(lfcShrunk < 0) %>% nrow()
text_label <- paste("Up-regulated:\nsRNAs: ",  n_sRNAs_up, "\nOther: ", n_other_up,"\nMicroorg: ", n_micro_up, collapse="\n")
text_label_down <- paste("Down-regulated:\nsRNAs: ",  n_sRNAs_down, "\nOther: ", n_other_down,"\nMicroorg: ", n_micro_down, collapse="\n")
ggplot(DE_T2acute_ann, aes(x = baseMean, y = lfcShrunk, colour = Class_toplot)) +
    geom_point(data = subset(DE_T2acute_ann, Class_toplot == "Non-significant"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.2) +
    geom_point(data = subset(DE_T2acute_ann, Class_toplot == "Other"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.3) +
    geom_point(data = subset(DE_T2acute_ann, Class_toplot == "Microorganism"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.3) +
    geom_point(data = subset(DE_T2acute_ann, Class_toplot == "miRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.9) +
    geom_point(data = subset(DE_T2acute_ann, Class_toplot == "snRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    #geom_point(data = subset(DE_T2acute_ann, Class_toplot == "scaRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    geom_point(data = subset(DE_T2acute_ann, Class_toplot == "snoRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    geom_point(data = subset(DE_T2acute_ann, Class_toplot == "piRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    geom_point(data = subset(DE_T2acute_ann, Class_toplot == "tRNA-derived"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    geom_point(data = subset(DE_T2acute_ann, Class_toplot == "tyRNA"), aes(x = baseMean, y =lfcShrunk), size=0.65, alpha=0.8) +
    #scale_alpha_discrete(range = c(0.9, 0.2)) +
    ggtitle("Severe (T2) expression") +
    xlab("baseMean") + 
    ylab("Log2 fold change") +
    scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
        labels = trans_format("log10", math_format(10^.x))) + 
    scale_colour_manual(values = c("#d53e4f", "#3288bd", "#ff8d50", "#b78bc0", "#50ff75", "#64b39a", "#CDAC8E", "#c9eeea", "#b2bbba"),  name = "",
                        breaks = c("miRNA","tRNA-derived", "snRNA", "snoRNA", "tyRNA", "piRNA", "Microorganism", "Other", "Non-significant")) +
    theme_light() +
    theme(plot.title = element_text(size = rel(2), hjust = 0.5),
          axis.title = element_text(size = rel(1.5)),
          panel.grid = element_blank()) +
    guides(color = guide_legend(override.aes = list(size = 3))) +
    annotate("text", x=40000, y=20, label=text_label, vjust=1, hjust=0, angle=0, size=4.5) +
    annotate("text", x=40000, y=-9, label=text_label_down, vjust=1, hjust=0, angle=0, size=4.5) +
    theme(legend.position = "bottom",
          axis.text.x = element_text(size=16, color="black"),
          axis.text.y = element_text(size=16, color="black"),
          axis.line.x = element_line(color="black"),
          axis.line.y = element_line(color="black")) +
    geom_hline(yintercept=0, size=0.3, color="darkgrey") + ylim(-15,20)

ggsave("/path/to/DEA_results/Visualizations/MAplot_T2acute_micro_withlegend.svg", height = 7, width = 8.5)
```


#### T2 mild

```{r}
## Create another column to indicate the type of RNAs only if it is significant
DE_T2mild_ann$Class_toplot <- ifelse(is.na(DE_T2mild_ann$RNA_class), "Other", DE_T2mild_ann$RNA_class)
DE_T2mild_ann$Class_toplot <- ifelse(grepl("miRNA-like|lncRNA|protein_coding|misc_RNA|rRNA|Mt_RNA|scaRNA", DE_T2mild_ann$RNA_class), "Other", DE_T2mild_ann$Class_toplot)
DE_T2mild_ann$Class_toplot <- ifelse(grepl("piR-cluster", DE_T2mild_ann$RNA_class), "piRNA", DE_T2mild_ann$Class_toplot)
DE_T2mild_ann$Class_toplot <- ifelse(DE_T2mild_ann$padj < 0.05, DE_T2mild_ann$Class_toplot, "Non-significant")
DE_T2mild_ann$Class_toplot <- factor(DE_T2mild_ann$Class_toplot, levels=c("miRNA", "tyRNA", "tRNA-derived", "snRNA", "snoRNA", "piRNA", "Microorganism", "Other", "Non-significant"))
```

```{r}
## MAplot
n_sRNAs_up <- DE_T2mild_ann %>% filter(!Class_toplot %in% c("Non-significant", "Other", "Microorganism")) %>% filter(lfcShrunk > 0) %>% nrow()
n_micro_up <- DE_T2mild_ann %>% filter(Class_toplot == "Microorganism") %>% filter(lfcShrunk > 0) %>% nrow()
n_other_up <- DE_T2mild_ann %>% filter(Class_toplot == "Other") %>% filter(lfcShrunk > 0) %>% nrow()
n_sRNAs_down <- DE_T2mild_ann %>% filter(!Class_toplot %in% c("Non-significant", "Other", "Microorganism")) %>% filter(lfcShrunk < 0) %>% nrow()
n_micro_down <- DE_T2mild_ann %>% filter(Class_toplot == "Microorganism") %>% filter(lfcShrunk < 0) %>% nrow()
n_other_down <- DE_T2mild_ann %>% filter(Class_toplot == "Other") %>% filter(lfcShrunk < 0) %>% nrow()
text_label <- paste("Up-regulated:\nsRNAs: ",  n_sRNAs_up, "\nOther: ", n_other_up,"\nMicroorg: ", n_micro_up, collapse="\n")
text_label_down <- paste("Down-regulated:\nsRNAs: ",  n_sRNAs_down, "\nOther: ", n_other_down,"\nMicroorg: ", n_micro_down, collapse="\n")
ggplot(DE_T2mild_ann, aes(x = baseMean, y = lfcShrunk, colour = Class_toplot)) +
    geom_point(data = subset(DE_T2mild_ann, Class_toplot == "Non-significant"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.2) +
    geom_point(data = subset(DE_T2mild_ann, Class_toplot == "Other"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.3) +
    geom_point(data = subset(DE_T2mild_ann, Class_toplot == "Microorganism"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.3) +
   geom_point(data = subset(DE_T2mild_ann, Class_toplot == "miRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.9) +
    geom_point(data = subset(DE_T2mild_ann, Class_toplot == "snRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    #geom_point(data = subset(DE_T2mild_ann, Class_toplot == "scaRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    geom_point(data = subset(DE_T2mild_ann, Class_toplot == "snoRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    geom_point(data = subset(DE_T2mild_ann, Class_toplot == "piRNA"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    geom_point(data = subset(DE_T2mild_ann, Class_toplot == "tRNA-derived"), aes(x = baseMean, y = lfcShrunk), size=0.65, alpha=0.8) +
    geom_point(data = subset(DE_T2mild_ann, Class_toplot == "tyRNA"), aes(x = baseMean, y =lfcShrunk), size=0.65, alpha=0.8) + 
    #scale_alpha_discrete(range = c(0.9, 0.2)) +
    ggtitle("Moderate (T2) expression") +
    xlab("baseMean") + 
    ylab("Log2 fold change") +
    scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
        labels = trans_format("log10", math_format(10^.x))) +  
    scale_colour_manual(values = c("#d53e4f", "#3288bd", "#ff8d50", "#b78bc0", "#50ff75", "#64b39a", "#CDAC8E", "#c9eeea", "#b2bbba"),  name = "",
                        breaks = c("miRNA","tRNA-derived", "snRNA", "snoRNA", "tyRNA", "piRNA", "Microorganism", "Other", "Non-significant")) +
    theme_light() +
    theme(plot.title = element_text(size = rel(2), hjust = 0.5),
          axis.title = element_text(size = rel(1.5)),
          panel.grid = element_blank()) +
    guides(color = guide_legend(override.aes = list(size = 3))) +
    annotate("text", x=40000, y=20, label=text_label, vjust=1, hjust=0, angle=0, size=4.5) +
    annotate("text", x=40000, y=-9, label=text_label_down, vjust=1, hjust=0, angle=0, size=4.5) +
    theme(legend.position = "none",
          axis.text.x = element_text(size=16, color="black"),
          axis.text.y = element_text(size=16, color="black"),
          axis.line.x = element_line(color="black"),
          axis.line.y = element_line(color="black")) +
    geom_hline(yintercept=0, size=0.3, color="darkgrey") + ylim(-15,20)

ggsave("/path/to/DEA_results/Visualizations/MAplot_T2mild_micro.png", height = 7, width = 8.5)
```


***

### Cleveland dot plots

```{r}
T1_acute_summary <- DE_T1acute_ann %>%
  dplyr::count(Class_toplot)
T1_acute_summary$Group <- "T1"
T1_mild_summary <- DE_T1mild_ann %>%
  dplyr::count(Class_toplot)
T1_mild_summary$Group <- "T1"
T2_acute_summary <- DE_T2acute_ann %>%
  dplyr::count(Class_toplot)
T2_acute_summary$Group <- "T2"
T2_mild_summary <- DE_T2mild_ann %>%
  dplyr::count(Class_toplot)
T2_mild_summary$Group <- "T2"

write.table(T1_acute_summary[,-3], "/path/to/DEA_results/T1_severe_summary.tsv", sep="\t", row.names=FALSE)
write.table(T2_acute_summary[,-3], "/path/to/DEA_results/T2_severe_summary.tsv", sep="\t", row.names=FALSE)
write.table(T1_mild_summary[,-3], "/path/to/DEA_results/T1_moderate_summary.tsv", sep="\t", row.names=FALSE)
write.table(T2_mild_summary[,-3], "/path/to/DEA_results/T2_moderate_summary.tsv", sep="\t", row.names=FALSE)

acute_summary <- rbind(T1_acute_summary, T2_acute_summary)
mild_summary <- rbind(T1_mild_summary, T2_mild_summary)

acute_summary$Class_toplot <- factor(acute_summary$Class_toplot, levels=c("miRNA","tRNA-derived", "snRNA", "snoRNA", "tyRNA", "piRNA", "Microorganism", "Other", "Non-significant"))
mild_summary$Class_toplot <- factor(mild_summary$Class_toplot, levels=c("miRNA","tRNA-derived", "snRNA", "snoRNA", "tyRNA", "piRNA", "Microorganism", "Other", "Non-significant"))
```

```{r}
acute_summary_filt <- acute_summary %>% filter(!Class_toplot %in% c("Microorganism", "Other", "Non-significant"))
acute_summary_filt$Class_toplot <- factor(acute_summary_filt$Class_toplot, levels=c("miRNA","tRNA-derived", "snRNA", "snoRNA", "tyRNA", "piRNA"))
acute_summary_filt$Group <- factor(acute_summary_filt$Group, levels=c("T2", "T1"))
ggplot(acute_summary_filt)+
    geom_linerange(aes(x = Class_toplot, ymin = 0, ymax = n, colour = Group, alpha=0.5), 
                   position = position_dodge(width = 0.5))+
    geom_point(aes(x = Class_toplot, y = n, colour = Group, size=2),
               position = position_dodge(width = 0.5))+
    scale_color_manual(values=c("#ED0000B2", "#da6a65")) +
    scale_x_discrete(limits=rev) +
    #scale_y_continuous(breaks=c(seq(0,37000, by= 2000)), limits = c(0, 37000)) +
    coord_flip() +
    theme_light() +
    theme(legend.title = element_blank(),
          legend.key.size=unit(1.5, 'cm'),
          legend.position="none",
          panel.grid.major.y = element_blank(),
          axis.text.x = element_text(size=16, color="black", vjust=0.5),
          axis.text.y = element_text(size=16, color="black"),
          axis.title = element_text(size = rel(1.75)),
          axis.text.x.top = element_blank(),
          axis.ticks.x.top = element_blank(),
          axis.line.x.top = element_blank()) +
    guides(alpha="none", size="none") + xlab("") + ylab("Number of sequences")
ggsave("/path/to/DEA_results/Visualizations/lollipop_number_seqs_acute_filt.svg", height = 5, width = 8)
```

```{r}
mild_summary_filt <- mild_summary %>% filter(!Class_toplot %in% c("Microorganism", "Other", "Non-significant"))
mild_summary_filt$Class_toplot <- factor(mild_summary_filt$Class_toplot, levels=c("miRNA","tRNA-derived", "snRNA", "snoRNA", "tyRNA", "piRNA"))
mild_summary_filt$Group <- factor(mild_summary_filt$Group, levels=c("T2", "T1"))
ggplot(mild_summary_filt)+
    geom_linerange(aes(x = Class_toplot, ymin = 0, ymax = n, colour = Group, alpha=0.5), 
                   position = position_dodge(width = 0.5))+
    geom_point(aes(x = Class_toplot, y = n, colour = Group, size=2),
               position = position_dodge(width = 0.5))+
    scale_color_manual(values=c("darkgreen", "lightgreen")) +
    scale_x_discrete(limits=rev) +
    #scale_y_continuous(breaks=c(seq(0,37000, by= 2000)), limits = c(0, 37000)) +
    coord_flip() +
    theme_light() +
    theme(legend.title = element_blank(),
          legend.key.size=unit(1.5, 'cm'),
          legend.position="none",
          panel.grid.major.y = element_blank(),
          axis.text.x = element_text(size=16, color="black", vjust=0.5),
          axis.text.y = element_text(size=16, color="black"),
          axis.title = element_text(size = rel(1.75)),
          axis.text.x.top = element_blank(),
          axis.ticks.x.top = element_blank(),
          axis.line.x.top = element_blank()) +
    guides(alpha="none", size="none") + xlab("") + ylab("Number of sequences")
ggsave("/path/to/DEA_results/Visualizations/lollipop_number_seqs_mild_filt.svg", height = 5, width = 8)
```


